on:
    push:
        branches:
            - master

permissions:
    contents: write
    pull-requests: write

name: Release Please

jobs:
    release-please:
        runs-on: ubuntu-latest
        env:
            FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
        steps:
            - uses: googleapis/release-please-action@v4
              with:
                  release-type: node
                  skip-github-pull-request: true
